const api = '/games/';
let games = [], activeFilter = 'all';
const $ = (selector) => document.querySelector(selector);
const grid = $('#gamesGrid'), dialog = $('#gameDialog'), form = $('#gameForm');

function esc(value) { const node = document.createElement('span'); node.textContent = value; return node.innerHTML; }
function toast(message) { const t = $('#toast'); t.textContent = message; t.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => t.classList.remove('show'), 2800); }
function genreColor(genre) { const colors = ['#b9a6ff','#f19c7b','#68d7c4','#f0cb75','#83aaff']; let n = 0; for (const char of genre) n += char.charCodeAt(0); return colors[n % colors.length]; }
function updateStats() { const total = games.length, done = games.filter(g => g.completed).length, avg = total ? games.reduce((s, g) => s + g.rating, 0) / total : 0, pct = total ? Math.round(done / total * 100) : 0; $('#totalCount').textContent = total; $('#heroCount').textContent = total; $('#completedCount').textContent = done; $('#completionLabel').textContent = done ? `${total - done} в очереди` : 'ещё впереди'; $('#averageRating').textContent = total ? avg.toFixed(1) : '—'; $('#progressValue').textContent = `${pct}%`; $('#progressBar').style.width = `${pct}%`; }
function render() { const term = $('#searchInput').value.trim().toLowerCase(); const shown = games.filter(g => (!term || `${g.title} ${g.genre}`.toLowerCase().includes(term)) && (activeFilter === 'all' || activeFilter === 'completed' ? g.completed : !g.completed)); grid.innerHTML = shown.map((game, i) => `<article class="game-card reveal" style="--accent:${genreColor(game.genre)}; --delay:${i * 55}ms"><div class="card-top"><span class="game-year">${game.year}</span><div class="card-menu"><button data-action="edit" data-id="${game.id}" aria-label="Редактировать">···</button></div></div><div class="game-art"><span>${esc(game.genre.slice(0, 1).toUpperCase())}</span><i></i></div><div class="game-info"><div><p>${esc(game.genre)}</p><h3>${esc(game.title)}</h3></div><b>${game.rating.toFixed(1)}</b></div><div class="card-bottom"><button class="status ${game.completed ? 'done' : ''}" data-action="complete" data-id="${game.id}"><span>${game.completed ? '✓' : '○'}</span>${game.completed ? 'Пройдено' : 'В процессе'}</button><button class="delete" data-action="delete" data-id="${game.id}" aria-label="Удалить игру">×</button></div></article>`).join(''); $('#emptyState').hidden = games.length !== 0; updateStats(); }
async function request(url = api, options) { const res = await fetch(url, options); if (!res.ok) { const data = await res.json().catch(() => ({})); throw new Error(data.detail || 'Не удалось выполнить запрос'); } return res.status === 204 ? null : res.json(); }
async function loadGames() { try { games = await request(); render(); } catch (e) { toast(`Ошибка API: ${e.message}`); } }
function openForm(game) { form.reset(); $('#gameId').value = game?.id || ''; $('#dialogTitle').textContent = game ? 'Изменить игру' : 'Добавить игру'; $('#title').value = game?.title || ''; $('#genre').value = game?.genre || ''; $('#year').value = game?.year || 2026; $('#rating').value = game?.rating || 8; $('#ratingOutput').textContent = (+$('#rating').value).toFixed(1); $('#completed').checked = game?.completed || false; dialog.showModal(); $('#title').focus(); }
['#openCreate','#openCreateAlt','#openEmpty'].forEach(id => $(id).addEventListener('click', () => openForm()));
$('#closeDialog').onclick = $('#cancelDialog').onclick = () => dialog.close(); $('#rating').oninput = e => $('#ratingOutput').textContent = (+e.target.value).toFixed(1);
form.addEventListener('submit', async e => { e.preventDefault(); const id = $('#gameId').value, body = { title: $('#title').value.trim(), genre: $('#genre').value.trim(), year: +$('#year').value, rating: +$('#rating').value, completed: $('#completed').checked }; try { await request(id ? `${api}${id}` : api, { method: id ? 'PUT' : 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(body) }); dialog.close(); toast(id ? 'Игра обновлена' : 'Игра добавлена в коллекцию'); await loadGames(); } catch (err) { toast(err.message); } });
grid.addEventListener('click', async e => { const button = e.target.closest('button[data-action]'); if (!button) return; const game = games.find(g => g.id === +button.dataset.id); if (button.dataset.action === 'edit') return openForm(game); if (button.dataset.action === 'delete' && !confirm(`Удалить «${game.title}»?`)) return; try { if (button.dataset.action === 'complete') await request(`${api}${game.id}/complete`, {method:'PATCH'}); if (button.dataset.action === 'delete') await request(`${api}${game.id}`, {method:'DELETE'}); toast(button.dataset.action === 'delete' ? 'Игра удалена' : 'Отмечено как пройдено'); await loadGames(); } catch(err) { toast(err.message); } });
$('#searchInput').addEventListener('input', render); $('#filters').addEventListener('click', e => { const button = e.target.closest('button'); if (!button) return; activeFilter = button.dataset.filter; document.querySelectorAll('.filter').forEach(b => b.classList.toggle('active', b === button)); render(); });
$('#recommendButton').onclick = async () => { try { const game = await request(`${api}recommend`); toast(`Ваш следующий мир: ${game.title}`); document.querySelector(`[data-id="${game.id}"]`)?.closest('.game-card')?.scrollIntoView({behavior:'smooth', block:'center'}); } catch (e) { toast('Нет непройденных игр с рейтингом от 7'); } };
loadGames();
